### ISSUE TITLE
A problem of PCA

### ISSUE THREAD

**Issue by nianr** [cxy1997/MNIST-baselines#2]
Thank you for your quality code!
There is an error occurred in file 'utils.py'. I did not edit the code after I cloned it from Github and my python version is 3.6.6, scikit-learn version is 0.20.2. The screenshot shows as followed. 
<img width="876" alt="screen shot 2018-12-26 at 10 53 27 pm" src="https://user-images.githubusercontent.com/26402409/50449334-b2ef0f80-0961-11e9-9887-d3f7a0e337c6.png">
My command is "python main.py --method lenet", just like the example of usages. 
Is it caused by my running environment? Or is by my operations?
Thank you!

**Comment by cxy1997** [comment]
I think your sklearn version is newer, and that's the cause of the problem. Thanks for pointing out. Let me update the code.

**Comment by cxy1997** [comment]
I've fixed the problem. Actually it's not about sklearn version. When @shinshiner merged his code of non-convolution methods, feature extraction intended for flattened data will be called unconditionally. However, in CNN settings, data is not flattened, which causes the problem. Thanks for reminding me!

**Comment by nianr** [comment]
> I've fixed the problem. Actually it's not about sklearn version. When @shinshiner merged his code of non-convolution methods, feature extraction intended for flattened data will be called unconditionally. However, in CNN settings, data is not flattened, which causes the problem. Thanks for reminding me!

The problem has been solved. Thanks!
